name: ndarray
description: N-Dimensional Arrays in Dart.
version: 0.0.1
homepage: dashflow-io.github.io/ndarray

environment:
  sdk: ">=3.0.0-19.0.dev <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  mustache_template: ^2.0.0
  ffi: ^2.0.1
  args: ^2.3.1
  cli_util: ^0.3.5

dev_dependencies:
  ffigen: ^7.2.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  grinder: ^0.9.2
  path: ^1.8.3
  glob: ^2.1.1
  yaml: ^3.1.1
