import 'dart:io';

import 'package:grinder/grinder.dart';

import 'contributors.dart';
import 'copyright.dart';
import 'utils.dart';

main(args) => grind(args);

@Task('Initialize stuff.')
void init() {
  log('Initializing stuff...');
  final ffigen = PubApp.global('ffigen');
  if (!ffigen.isActivated) {
    log('Activating ffigen...');
    ffigen.activate();
  }
}

@DefaultTask('Generate/Update bindings to native code.')
@Depends(init)
void bindings([String configFile = 'ffigen.yaml']) {
  PubApp.global('ffigen').run(['--config', configFile]);
}

@Task('Compile stuff.')
@Depends(bindings)
void compile() {
  log('Compiling stuff...');
}

@Task('Deploy stuff.')
@Depends(compile)
void deploy() {
  log('Deploying stuff...');
}

@Task('List contributors in lexicographic order.')
void listContributors() {
  log('Extracting contributors...');
  final contributorsList = contributors();
  log('\nContributors founded:');
  contributorsList.forEach((contributor) => log(' * $contributor'));
}

@Task('Generate/update a CONTRIBUTORS file.')
void updateContributors() {
  log('Extracting contributors...');
  var contributorList = contributors().join('\n');
  log('Generating/Updating the CONTRIBUTORS file...');
  var contributorsFile = File('CONTRIBUTORS');
  var thisScript = relativePath(Platform.script);
  contributorsFile.writeAsString("""
# This file is generated by $thisScript.
#
# Contributors listed in alphabetical order.

$contributorList
""");
}

@Task('Generate/update the copyright headers.')
void copyrightHeaders() {
  log('Loading copyright.yaml...');
  final copyright = loadCopyright();
  log('Applying copyright headers');
  copyright.apply();
}
