# Workflow name:
name: update_contributors

# Workflow triggers:
on:
  pull_request:
    branches:
      - main
    types:
      - closed

  # Allow the workflow to be manually run:
  workflow_dispatch:

# Workflow jobs:
jobs:

  # Define a job for updating the contributors list...
  update-contributors:

    # Define a display name:
    name: 'Update contributors'

    # Only run this job if the pull request was merged (or the job was triggered manually):
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    # Define the type of virtual host machine:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:

      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          # Specify whether to remove untracked files before checking out the repository:
          clean: true

          # Refers to the development branch:
          ref: 'main'

          # Fetch entire history:
          fetch-depth: 0

          # Specify whether to download Git-LFS files:
          lfs: false
        timeout-minutes: 10
      
      # Install Flutter:
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      # Run pub get:
      - name: Run pub get
        run: flutter pub get

      # Activate Grinder Globally:
      - name: Activate Grinder Globally
        run: flutter pub global activate grinder

      # Update the contributors list:
      - name: 'Update contributors'
        id: update-contributors
        run: |
          grind update-contributors

          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Configure Git
        run: |
          git config --global user.email "ci@local"
          git config --global user.name CI

      # Create a pull request:
      - name: 'Create pull request'
        if: steps.update-contributors.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          title: 'Update list of contributors'
          body: |
            This PR

            -   updates the list of contributors

          commit-message: 'Update list of contributors'
          labels: |
            documentation
            automated-pr
          team-reviewers: |
            dashflow-reviewers
          branch: update-contributors
          delete-branch: true

      # Create a pull request summary:
      - name: 'Create summary'
        run: |
          echo "# :tada: Pull Request created! :tada:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pull request ${{ steps.cpr.outputs.pull-request-number }} was successfully ${{ steps.cpr.outputs.pull-request-operation }}."
          echo ":link: [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})." >> $GITHUB_STEP_SUMMARY
          echo "Head SHA: [${{ steps.cpr.outputs.pull-request-head-sha }}](${{ steps.cpr.outputs.pull-request-url }}/commits/${{ steps.cpr.outputs.pull-request-head-sha }})." >> $GITHUB_STEP_SUMMARY
